version: "3.8"

services:
  studycase-postgresql:
    image: docker.io/bitnami/postgresql:16
    container_name: studycase-postgresql
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "POSTGRESQL_DATABASE=liquibase-demo-db"
      - "POSTGRESQL_USERNAME=dev"
    ports:
      - "5432:5432"
    networks:
      studycase-network:
    volumes:
      - "./volumes/studycase-postgresql:/bitnami/postgresql"

networks:
  studycase-network:
    driver: bridge